### PR TITLE
Fix cancel order

### LINKED ISSUE #11: Order can not always be canceled
#### Expected Behavior

Orders are being canceled at all times without issues.

#### Actual Behavior
Some orders can not always be canceled,  it happens in multiple occasions but It seems I found one way to reliably reproduce it. (See reproducing the problem)

#### Potential Solution

Don't raise an error when the status is `CancelPending` here: https://github.com/QuantConnect/Lean.Brokerages.ByBit/blob/a5b3f02c04838b5bb0a66e496b8ca958f0518a95/QuantConnect.BybitBrokerage/BybitBrokerage.Brokerage.cs#L201-L206

It seems that sometimes the order status is already `CancelPending` even though the cancel request was never sent to the brokerage.

#### Reproducing the Problem

- Create an empty algo using the bybit brokerage. Which calls liquidate after startup.
- Manually create an order in the exchange
- Start the algorithm, the following error should pop up:

```
20231129 06:56:56.592 ERROR:: Brokerage Warning: Order already canceled or cancellation submitted
20231129 06:56:56.593 ERROR:: Brokerage failed to cancel order with id 1
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by arodus**
#### Description
Remove the status check in the brokerage. 

#### Related Issue

Fixes #11 

#### How Has This Been Tested?

Manual testing on live.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [ ] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

File: QuantConnect.BybitBrokerage/BybitBrokerage.Brokerage.cs [hunk 1]
```diff
@@ -198,10 +198,9 @@ public override bool CancelOrder(Order order)
                 return;
             }
 
-            if (order.Status is OrderStatus.Canceled or OrderStatus.CancelPending)
+            if (order.Status is OrderStatus.Canceled)
             {
-                OnMessage(new BrokerageMessageEvent(BrokerageMessageType.Warning, -1,
-                    "Order already canceled or cancellation submitted"));
+                OnMessage(new BrokerageMessageEvent(BrokerageMessageType.Warning, -1, "Order already canceled"));
```
Comment (Martin-Molinero) [inline QuantConnect.BybitBrokerage/BybitBrokerage.Brokerage.cs:203]: Thank you! 👍  Yes, it's Lean transaction handler that set's the CancelPending state before sending the order cancel request to the brokerage https://github.com/QuantConnect/Lean/blob/master/Engine/TransactionHandlers/BrokerageTransactionHandler.cs#L477

**Review by Martin-Molinero — APPROVED** [review]
