### PR TITLE
Fix: handle `PlaceOrder()` exception internally in brokerage

### LINKED ISSUE #19: Improve Order Error Message
#### Expected Behavior
Users are informed of the cause of invalid orders.

#### Actual Behavior
The algorithm received the following information

> 2024-03-05T15:05:00.7148461Z TRACE:: LiveTradingResultHandler.OrderEvent(): Time: 03/05/2024 15:05:00 OrderID: 2 EventID: 1 Symbol: BTCUSDT Status: **Invalid Quantity**: -0.047175 Message: **Brokerage failed to place orders**: [2] BrokerId: 

and we don't know why.

When we inpect the syslog, we can read:

> ErrorMessage: Cross Margin Trading not yet supported by the selected coin

```
2024-03-05T15:05:00.7146835Z ERROR:: BrokerageTransactionHandler.HandleSubmitOrderRequest():  System.Exception: ByBitApiClient request failed: [200] OK, Content: {"retCode":170037,"retMsg":"Cross Margin Trading not yet supported by the selected coin","result":{},"retExtInfo":{},"time":1709651100616}, ErrorCode: 170037 ErrorMessage: Cross Margin Trading not yet supported by the selected coin
   at QuantConnect.Brokerages.Bybit.Api.BybitTradeApiEndpoint.PlaceOrder(BybitProductCategory category, Order order, Boolean useMargin)
   at QuantConnect.Brokerages.Bybit.BybitBrokerage.g.d()
   at QuantConnect.Brokerages.BrokerageConcurrentMessageHandler`1.WithLockedStream(Action code) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/LeanEnterprise/Brokerages/BrokerageConcurrentMessageHandler.cs:line 82
   at QuantConnect.Brokerages.Bybit.BybitBrokerage.PlaceOrder(Order order)
```

The user should receive that error message instead of "Brokerage failed to place orders" or as a Brokerage Message.

#### Potential Solution
N/A

#### Reproducing the Problem
`SetHoldings("BTCUSDT", 1);`
then
`SetHoldings("BTCUSDT", 0);`

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

### PR DESCRIPTION
**Pull request by Romazes**
#### Description

Handling an error **before** changing:
```
2025-03-25T13:26:02.7147555Z TRACE:: BrokerageTransactionHandler.Process(): 03/25/2025 13:26:00 UTC: Submit Order: (1) - OrderId: 1 (BrokerId: ) New Market order for 2544.48 units of XRPUSDT  Status: Unprocessed

2025-03-25T13:26:04.1647507Z ERROR:: BrokerageTransactionHandler.HandleSubmitOrderRequest():  System.Exception: ByBitApiClient request failed: [200] OK, Content: {"retCode":170344,"retMsg":"Symbol is not supported on Margin Trading.","result":{},"retExtInfo":{},"time":1742909164851}, ErrorCode: 170344 ErrorMessage: Symbol is not supported on Margin Trading.
   at QuantConnect.Brokerages.Bybit.Api.BybitTradeApiEndpoint.PlaceOrder(BybitProductCategory category, Order order, Boolean useMargin) in D:\Source\Lean.Brokerages.ByBit\QuantConnect.BybitBrokerage\Api\BybitTradeApiEndpoint.cs:line 85
   at QuantConnect.Brokerages.Bybit.BybitBrokerage.<>c__DisplayClass3_0.<PlaceOrder>b__0() in D:\Source\Lean.Brokerages.ByBit\QuantConnect.BybitBrokerage\BybitBrokerage.Brokerage.cs:line 141
   at QuantConnect.Brokerages.BrokerageConcurrentMessageHandler`1.WithLockedStream(Action code)
   at QuantConnect.Brokerages.Bybit.BybitBrokerage.PlaceOrder(Order order) in D:\Source\Lean.Brokerages.ByBit\QuantConnect.BybitBrokerage\BybitBrokerage.Brokerage.cs:line 139
   at QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler.<HandleSubmitOrderRequest>b__64_0(Order o) in Engine\TransactionHandlers\BrokerageTransactionHandler.cs:line 873
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler.HandleSubmitOrderRequest(SubmitOrderRequest request) in Engine\TransactionHandlers\BrokerageTransactionHandler.cs:line 873

2025-03-25T13:26:04.1744623Z TRACE:: LiveTradingResultHandler.OrderEvent(): Time: 03/25/2025 13:26:00 OrderID: 1 EventID: 1 Symbol: XRPUSDT Status: Invalid Quantity: 2544.48 Message: Brokerage failed to place orders: [1] BrokerId: 
```

Handling an error **after** changing:
```
2025-03-25T13:43:01.5555137Z TRACE:: BrokerageTransactionHandler.Process(): 03/25/2025 13:43:00 UTC: Submit Order: (1) - OrderId: 1 (BrokerId: ) New Market order for 2544.64 units of XRPUSDT  Status: Unprocessed

2025-03-25T13:43:03.9165361Z TRACE:: LiveTradingResultHandler.OrderEvent(): Time: 03/25/2025 13:43:03 OrderID: 1 EventID: 1 Symbol: XRPUSDT Status: Invalid Quantity: 2544.64 Message: Bybit Order Event: ByBitApiClient request failed: [200] OK, Content: {"retCode":170344,"retMsg":"Symbol is not supported on Margin Trading.","result":{},"retExtInfo":{},"time":1742910183727}, ErrorCode: 170344 ErrorMessage: Symbol is not supported on Margin Trading. BrokerId: 
```

#### Related Issue

closes #19 

#### Motivation and Context

Handle exception messages in a more graceful and informative manner for users.

#### Requires Documentation Change

N/a

#### How Has This Been Tested?

- trade some market orders with using the Lean algo.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

### CODE REVIEW

**Review by Martin-Molinero — APPROVED** [review]

File: QuantConnect.BybitBrokerage/BybitBrokerage.Brokerage.cs [hunk 1]
```diff
@@ -134,21 +134,31 @@ public override bool PlaceOrder(Order order)
...
-            var result = ApiClient.Trade.PlaceOrder(GetBybitProductCategory(order.Symbol), order,
-                useMargin: _algorithm.BrokerageModel.AccountType == AccountType.Margin);
+            var result = default(Models.Requests.BybitUpdateOrderResponse);
+            try
+            {
+                result = ApiClient.Trade.PlaceOrder(GetBybitProductCategory(order.Symbol), order,
+                    useMargin: _algorithm.BrokerageModel.AccountType == AccountType.Margin);
+            }
+            catch (Exception ex)
+            {
```
Comment (AlexCatarino) [inline QuantConnect.BybitBrokerage/BybitBrokerage.Brokerage.cs:146]: Is the `OrderId` available in the exception? If so, we should call
`order.BrokerId.Add(result.OrderId);`
before the order event, so users can use the `OrderId` to ask the brokerage if they have to.
